# Étape 1 : Utilise  une image .NET officielle
FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80

# Étape 2 : Ajoute l'image SDK .NET pour la construction de l'application
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["IdentityServerProject/IdentityServerProject.csproj", "IdentityServerProject/"]
RUN dotnet restore "IdentityServerProject/IdentityServerProject.csproj"

COPY . .
WORKDIR "/src/IdentityServerProject"
RUN dotnet build "IdentityServerProject.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "IdentityServerProject.csproj" -c Release -o /app/publish

# Étape 3 : Crée l'image finale
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "IdentityServerProject.dll"]
