version: '3.4'

services:
  # Service pour la base de données SQL Server
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword123
    ports:
      - "1433:1433" # Expose le port SQL Server
    networks:
      - mynetwork
    volumes:
      - sql_data:/var/opt/mssql

  # Service pour ton application .NET Core
  web:
    build:
      context: .
    container_name: identityserver-app
    ports:
      - "5000:80"  # Le port 5000 de l'hôte est mappé au port 80 du conteneur
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=IdentityDb;User Id=sa;Password=YourStrongPassword123;
    depends_on:
      - sqlserver
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  sql_data:
